### ISSUE TITLE
Python 3.4 Resource Warning

### ISSUE THREAD

**Issue by ronin8600** [gawel/WSGIProxy2#11]
I'm getting a resource warning (socket not being closed) when using WSGIProxy2 with bottle.  

It looks like the connection is not being explicitly closed in HttpClient.**call**.  I tried adding a 'conn.close()' before the return and it appears to have fixed the warning.

**Comment by gawel** [comment]
The thing is that when you need a "Keep-Alive" Connection you don't want to close it

**Comment by djeebus** [comment]
I'm running into this error as well. It seems like the "Keep-Alive" header doesn't apply here. The connection is being thrown away after use, so there's no way to submit a second request. Or am I reading `HttpClient.__call__` wrong? The `conn.close()` befor return solves the error for me as well.

**Comment by gawel** [comment]
It depend which client your using. It may be true with the one based on python builtin but not with requests/urllib3

**Comment by djeebus** [comment]
Oh! Right, I'm talking specifically about this client: https://github.com/gawel/WSGIProxy2/blob/8de5c974d20279e8c7394e5e70441e7502192a8c/wsgiproxy/proxies.py#L74

I fixed it here, would this break anything? https://github.com/gawel/WSGIProxy2/compare/master...djeebus:clean-up-connection

**Comment by gawel** [comment]
I guess it's fine if the tests pass. PR welcome :)

**Comment by djeebus** [comment]
PR incoming! =) Thanks!
