### ISSUE TITLE
Query string lost with Werkzeug

### ISSUE THREAD

**Issue by fmang** [gawel/WSGIProxy2#24]
When I tried to use WSGIProxy2 with Werkzeug’s test client, I noticed the query string gets lost. Here’s how to reproduce:

```python
import werkzeug.test
import wsgiproxy

proxy = wsgiproxy.HostProxy("http://localhost:8080")
client = werkzeug.test.Client(proxy)
client.get("/x?a=b")
```

If you have an HTTP server running at localhost:8080, you’ll notice the query string is missing in the access log.

The issue is located here: https://github.com/gawel/WSGIProxy2/blob/0.4.6/wsgiproxy/proxies.py#L149-L166

It’s caused by Werkzeug’s definition of REQUEST_URI which does not contain the query string. I think this is unusual, but since REQUEST_URI is not standardized they’re not objectively wrong. It’s hard to please every WSGI server, each with their own interpretation of the environment, but PEP 3333 is clear: https://www.python.org/dev/peps/pep-3333/#url-reconstruction

Python’s standard library also provide an URL reconstruction method that should be a good fit: https://docs.python.org/3.8/library/wsgiref.html#wsgiref.util.request_uri

I don’t know why in WSGIProxy2 the non-standard REQUEST_URI and RAW_URI take precedence over the standard variables, but I daresay implementations conforming to PEP 3333 should work. However, if for some reason you *had* to make it that way, how about adding the query string after REQUEST_URI when it doesn’t already contain one even though QUERY_STRING is not empty?

**Comment by gawel** [comment]
As I remember it is because standard variables are decoded by wsgi servers

For example `%2F` may become a `/` and the proxied application may not like it

But I'm not really sure / maybe things changed in PEP 3333

**Comment by fmang** [comment]
That makes sense. A proxy should use the rawest data is has.

I don’t think REQUEST_URI has ever been standardized in PEP 3333.

I plan to make an issue for Werkzeug too, because as far as I can tell,
REQUEST_URI is usually expected to contain the query string. If they
accept the change, you don’t have to do anything, but maybe you could
still make WSGIProxy2 a bit more robust. For example:

```python
        if 'RAW_URI' in environ:
            path_info = environ['RAW_URI']
        elif 'REQUEST_URI' in environ:
            path_info = environ['REQUEST_URI']
        else:
	    # ...

	# Unindent the query string processing to make it common to the
	# 3 cases and add the condition `'?' not in path_info` to
	# prevent the query string from being duplicated:

        query_string = environ['QUERY_STRING']
        if query_string and '?' not in path_info:
            path_info += '?' + query_string
```

https://github.com/gawel/WSGIProxy2/blob/0.4.6/wsgiproxy/proxies.py#L164-L166

**Comment by fmang** [comment]
Looks like that wasn’t Werkzeug’s intention to strip the query string. See https://github.com/pallets/werkzeug/issues/1781

I’m closing this issue. Whether to add the safeguard is up to you.
